version: "3.8"

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    container_name: backend
    volumes:
      - ./back:/code
      - ./media:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=django-insecure-kjgjj%wa2i=z&t+=m400r-9h(bqrxd+23kjt*&y&kk6=i4%ebr
      - DB_HOST=db
      - DB_NAME=dentapp
      - DB_USER=crentist
      - DB_PASSWORD=tesca123
      - DB_PORT=5432
      - SITE_URL="http://citassalud.com.mx"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --no-input&&
             python manage.py initadmin &&
             gunicorn --bind 0.0.0.0:8000 dentappointment.wsgi"
    networks:
      - backend-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    container_name: frontend
    volumes:
      - ./front:/app
    networks:
      - frontend-network
      - backend-network
    restart: always

  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dentapp
      POSTGRES_USER: crentist
      POSTGRES_PASSWORD: tesca123
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: always

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./media:/app/media
      - static_volume:/app/staticfiles
      - ./front/dist:/usr/share/nginx/html # Mount Vue.js dist folder to serve as Nginx HTML
    depends_on:
      - backend
    networks:
      - backend-network
      - frontend-network
    restart: always

networks:
  backend-network:
  frontend-network:

volumes:
  postgres_data:
  static_volume:
