services:
  backend:
    build:
      context: ./back
    container_name: backend
    command:
      ["gunicorn", "--bind", "0.0.0.0:8000", "my_project.wsgi:application"]
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=django-insecure-kjgjj%wa2i=z&t+=m400r-9h(bqrxd+23kjt*&y&kk6=i4%ebr
      - DB_HOST=127.0.0.1
      - DB_NAME=dentapp
      - DB_USER=crentist
      - DB_PASSWORD=tesca123
      - DB_PORT=5432

  frontend:
    build:
      context: ./appointment-front
    container_name: frontend
    volumes:
      - ./appointment-front:/app
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dentapp
      POSTGRES_USER: crentist
      POSTGRES_PASSWORD: tesca123
    ports:
      - "5432:5432"

volumes:
  postgres_data:
