# Generated by Django 4.2.6 on 2024-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='id_service',
        ),
        migrations.AddField(
            model_name='treatment',
            name='services',
            field=models.ManyToManyField(to='appointment.service'),
        ),
    ]
