# Generated by Django 4.2.6 on 2024-05-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_treatment_id_service_treatment_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
